#!/usr/bin/env bash
# **The editor pane, end to end**: a session that edited a file, opened in rano by chord and
# by click, read as a review, sent back into the composer, and closed — with the head, not
# rano, still running at the end.
#
# The session is `fixtures/edit.jsonl`, generated by the test
# `the_acceptance_fixture_is_this_session` (crates/tui/src/app/tests/editor.rs): the edit of
# line 11 of notes.txt, which this spec writes into the workspace with the change applied.
. "$(dirname -- "${BASH_SOURCE[0]}")/lib.sh"

for i in $(seq 1 30); do echo "line $i"; done > "$WORK/notes.txt"
# multibuffer on, as the operator runs rano: the pane's empty starting buffer must still be
# replaced by the file rather than kept beside it as a [1/2].
mkdir -p "$CONFIG/rano"
echo 'multibuffer = true' > "$CONFIG/rano/config.toml"
start --replay "$FIXTURES/edit.jsonl"

spec "the edit row is there to open"
wait_for "Edited notes.txt"
wait_for "Line eleven is fixed."
settle

spec "ctrl-] opens the newest change as a review"
press C-]
wait_for "Review notes.txt (unified)"
expect "M-s: send your place"
expect "-old 11"
expect "+line 11"
expect "Ln 11, Col 1"
expect "ctrl-] to the composer"
expect_not "[2/2]"

spec "s turns the review into a split"
press s
wait_for "Review notes.txt (split)"
expect_line "11 - old 11" "11 + line 11"

spec "Esc lands in the text on the changed line"
press Escape
wait_gone "Review notes.txt"
expect "11 line 11"
expect "Ln 11, Col 1"

spec "alt-s sends the place into the composer, and the composer has the keyboard"
press M-s
wait_for "notes.txt:11"
# Relative, as the row named it: a replay has no session workspace, so the head's directory.
expect_line "›" "› notes.txt:11"
expect "ctrl-] back to the editor"

spec "nothing was sent: the place waits in the composer for an instruction"
expect_not "▌ notes.txt:11"

spec "ctrl-] goes back into the pane, and ctrl-q closes it without quitting the head"
press C-]
wait_for "ctrl-] to the composer"
press C-q
wait_gone "rano 0."
expect "Edited notes.txt"
expect "please fix line eleven"

spec "a click on the edit row opens it again"
click "Edited notes.txt"
wait_for "Review notes.txt"

spec "a click on a row that is no file opens nothing"
press C-q
wait_gone "Review notes.txt"
click "Line eleven is fixed."
settle
expect_not "Review notes.txt"
expect_not "rano 0."

done_spec
